# Debian 12.1 (Bookworm)
# Includes Python 3.11 and Pip
FROM python:bookworm

# Install git and sshd
RUN apt update
RUN apt install git openssh-server -y

# Copy assets
COPY container-assets /

# Create users
RUN for user in `cat /users.txt`; do \
    adduser --comment "" $user && \
    echo "$user:$user-tx23" | chpasswd; done

# Allow SSH
EXPOSE 22
ENTRYPOINT service ssh restart && /bin/bash