# Debian 12.1 (Bookworm)
# Includes Python 3.11 and Pip
FROM python:bookworm

# Install git and sshd
RUN apt update
RUN apt install git openssh-server -y
RUN systemctl enable ssh

# Copy assets
COPY container-assets /

# Create users
RUN for user in `cat /container-assets/users.txt`; do \
    adduser --comment "" $user && \
    echo "$user:$user-tx23" | chpasswd; done

CMD ["/usr/sbin/sshd", "-D"]