# Debian 12.1 (Bookworm)
# Includes Python 3.11 and Pip
FROM python:bookworm

# Install git, sshd, pip, and the text editors
RUN apt update
RUN apt install -y --no-install-recommends \
    git \
    openssh-server \
    pip \
    vim nano emacs

# Copy assets
COPY container-assets /

# Create users
RUN for user in `cat /users.txt`; do \
    adduser --comment "" $user && \
    echo "$user:$user-tx23" | chpasswd; done

# Allow SSH
EXPOSE 22
ENTRYPOINT service ssh restart && /bin/bash